### ISSUE TITLE
Adding milestone and/or labels deletes issue contents

### ISSUE THREAD

**Issue by tonyarnold** [Me1000/issues#129] opened 2012-03-02 11:26 UTC
I've seen this quite a bit, and sadly it's just happened with a client issue. Not sure what I can provide to help track this down, but let me know.

**Comment by Me1000** [comment] 2012-03-04 01:58
This is fixed in the final version. Apologies for this, I thought I had it nailed down in a previous beta, but it turns out there was a 2nd issue causing it.

**Closed as completed by Me1000** 2012-03-04 01:58 UTC

**Comment by tonyarnold** [comment] 2012-03-04 02:49
Thanks Randy — I've just installed 1.0 :)

**Comment by Me1000** [comment] 2012-03-04 02:50
Please let me know if you see it again. I can't believe I missed it for so many betas (I actually think it might have been a regression), but I've tested it pretty heavily recently.

**Comment by tonyarnold** [comment] 2012-03-04 04:08
Will do :)
