### ISSUE TITLE
Comments wrap after couple of words

### ISSUE THREAD

**Issue by donkeytastic** [Me1000/issues#217] opened 2012-11-23 06:37 UTC
Comments field text wraps after only about a dozen characters. Still displays without carriage returns once submitted though.

**Comment by Appwerks** [comment] 2012-12-02 23:03
Noticed the same thing. The comment body text area accepts 11 characters per line and only 5 lines are visible. Line breaks do not show up on save.

**Comment by Me1000** [comment] 2012-12-02 23:05
This is a known bug on iOS 6. Closed as duplicate of #207

**Closed as completed by Me1000** 2012-12-02 23:05 UTC
