### ISSUE TITLE
Can't swipe off master view

### ISSUE THREAD

**Issue by bobspryn** [Me1000/issues#137] opened 2012-03-14 05:08 UTC
I switched to a vertical view and did the swiping from off the side of the bezel to show the list of issues for a repository. I can't seem to swipe it back off. OS 5.1

**Comment by GiK** [comment] 2012-03-14 19:21
See issue #136 - swipe right-to-left on master view's nav bar to dismiss.

**Comment by Me1000** [comment] 2012-03-16 22:01
Swipe the top of the sidebar to hide it, I'm looking into ways to make this more apparent.

**Comment by Me1000** [comment] 2012-03-16 22:02
Closing as a dupe of #136

**Closed as completed** 2012-03-16 22:03 UTC
