### ISSUE TITLE
Show me my repos list is incomplete

### ISSUE THREAD

**Issue by endash** [Me1000/issues#146] opened 2012-03-18 04:35 UTC
The show me my repos list gives me only a handful of repos to choose from. If I were a betting man, I'd wager it's showing me my oldest repos only.

**Comment by Me1000** [comment] 2012-03-18 19:13
Private repos are not visible (fixed pending Apple's review), repos with issue turned off are not visible (by design), everything else should be though... Can you confirm this?

**Comment by endash** [comment] 2012-03-18 19:21
Ah, yep, it's all my private repos that aren't showing up. I didn't consider that as a possibility because it's showing me _other_ private repos I'm a contrib on, just not my own.

Although, now that I dig into it it's also not showing me public, issue enabled repos for orgs I'm a member of. RestKit, for one, is one I definitely know should be showing up.

**Comment by Me1000** [comment] 2012-03-18 19:23
Awesome, then this will be fixed when the next update is released. Close as dupe of #132

**Comment by Me1000** [comment] 2012-03-18 19:24
ummm, reopening as I'm an idiot and totally skipped over the last part...

**Comment by Me1000** [comment] 2012-03-20 17:32
Can you tell me if these org repos you're not seeing are private?

**Comment by endash** [comment] 2012-03-20 17:37
One org I'm a member of (https://github.com/restkit/RestKit) has several public repos.

**Comment by Me1000** [comment] 2012-03-22 06:23
Are you on testflight? Of not mind creating an account to join my beta?

If you're cool with that message me your account email address and I'll add you to the project. :)

**Comment by endash** [comment] 2012-03-22 18:45
Hey yeah I added my email to my github profile.

**Closed as completed** 2012-03-27 05:39 UTC
Labels: Bug
