### ISSUE TITLE
App crashes on every new issue

### ISSUE THREAD

**Issue by alexbosworth** [Me1000/issues#174] opened 2012-04-11 07:20 UTC
Issue isn't posted and what was written and app starts in fresh state with all that was written erased

This is on a private repo

**Comment by Me1000** [comment] 2012-04-11 19:27
Sorry about that. I submitted an update that fixes this yesterday. 
To avoid losing your app state, close the app right after you login. Then you can reopen it. I'll work on getting the repos to instasave when you add them.

Closing as a dupe of #172

Again, sorry for the issues.

**Closed as completed by Me1000** 2012-04-11 19:27 UTC
