### ISSUE TITLE
Refresh doesn't work

### ISSUE THREAD

**Issue by donkeytastic** [Me1000/issues#218] opened 2012-11-25 00:20 UTC
After refreshing the app and restarting does not update issues. Issues that were closed over a day ago still show in open list and and in an open state.

**Comment by Me1000** [comment] 2012-11-25 00:24
You're right, refresh actually just checks for new issues, currently.

**Comment by Me1000** [comment] 2012-12-29 20:01
Closed as dupe of #130

**Closed as completed** 2012-12-29 20:02 UTC
Labels: Bug
