### ISSUE TITLE
Github -> GitHub

### ISSUE THREAD

**Issue by bryanveloso** [Me1000/issues#191] opened 2012-05-06 19:57 UTC
I realize this looks small and inconsequential. :)

The "canonical" way to write github with capital letters is GitHub. It would feed my soul as one of its designers to see it that way. :)

**Comment by Me1000** [comment] 2012-05-07 04:57
Totally! I've updated the iTunes description, should be rolling out soon (No idea how long it takes, I've never done that before). 

I've also updated it in the info modal window, and in the non-retina login text. I have an update awaiting review already, but I may reject it If I hear back from Apple on a crashing bug some users are reporting (and I can't reproduce). So the "GitHub" text update will be in one of the next two releases!

Please let me know if there's something I've overlooked!

I hope you all like BugHub! :)

**Comment by bryanveloso** [comment] 2012-05-07 21:58
@Me1000 — Thank you! I know a few of the others use it, but I'm definitely a happy user. :)

**Comment by Me1000** [comment] 2012-05-15 23:25
Fix has landed!

**Closed as completed by Me1000** 2012-05-15 23:25 UTC
Labels: Fixed Pending Release
