### ISSUE TITLE
comments are confined to a very small space in the comment entry view

### ISSUE THREAD

**Issue by besi** [Me1000/issues#214] opened 2012-10-16 16:24 UTC
when I add a comment it seems that it is confined to a space of approx 40x40 pixels. 

i tried to add an example before but then the app crashed (#213)

**Comment by Me1000** [comment] 2012-10-16 16:29
Yeah, this is a duplicate of #207. Looking for a fix, but it's difficult since I can't reproduce it myself. :(
Can you please confirm that this is happening on a 3rd generation iPad running iOS6?

**Closed as completed by Me1000** 2012-10-16 16:29 UTC
