### ISSUE TITLE
Filter by assignee not working

### ISSUE THREAD

**Issue by ghost** [Me1000/issues#177] opened 2012-04-13 07:25 UTC
I have several private repositories which I am a collaborator on. Filter by assignee only works on these projects if I select myself. Selecting other assignees just gives a blank list.

**Comment by Me1000** [comment] 2012-04-13 16:10
Dupe of #173, closing.

Thanks for the report

**Closed as completed by Me1000** 2012-04-13 16:10 UTC

**Comment by Me1000** [comment] 2012-04-17 00:31
Just a heads up, this should be fixed now with the latest update in the App Store.
