### ISSUE TITLE
Textfield when commenting issue allows max 12 letters

### ISSUE THREAD

**Issue by pavsaund** [Me1000/issues#221] opened 2013-01-04 07:39 UTC
When commenting an issue on the ipad(3) and ios 6.0.1 the text area (white) covers the entire screen, but the width of text per line is maximim 12 letters.

**Comment by Me1000** [comment] 2013-01-04 07:40
Thanks!

This is a duplicate of #207 and is fixed pending Apple's review!

**Closed as completed by Me1000** 2013-01-04 07:40 UTC

**Comment by pavsaund** [comment] 2013-01-04 07:44
thanks, didn`t see the other issue :)
